-- 1. ตาราง customer_groups
CREATE TABLE IF NOT EXISTS public.customer_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name CHARACTER VARYING NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. ตาราง food_groups
CREATE TABLE IF NOT EXISTS public.food_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. ตาราง food_mappings
CREATE TABLE IF NOT EXISTS public.food_mappings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_id BIGINT,
    stock_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. ตาราง food_prices
CREATE TABLE IF NOT EXISTS public.food_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_id BIGINT,
    customer_group_id BIGINT,
    price NUMERIC,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 5. ตาราง food_stocks
CREATE TABLE IF NOT EXISTS public.food_stocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_name TEXT,
    quantity NUMERIC,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 6. ตาราง foods
CREATE TABLE IF NOT EXISTS public.foods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name CHARACTER VARYING NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    requires_stock BOOLEAN,
    category_id BIGINT
);

-- 7. ตาราง locations
CREATE TABLE IF NOT EXISTS public.locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 8. ตาราง orders
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    customer_group TEXT,
    total_price NUMERIC,
    total_qty BIGINT,
    items JSONB,
    phone TEXT,
    location_name TEXT,
    zone_name TEXT,
    order_date DATE,
    status TEXT
);

-- 9. ตาราง zones
CREATE TABLE IF NOT EXISTS public.zones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    location_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);
