-- -------------------------------------------------------------
-- 1. ตารางกลุ่มลูกค้า (customer_groups)
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS customer_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name CHARACTER VARYING NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- -------------------------------------------------------------
-- 2. ตารางกลุ่มอาหาร/หมวดหมู่ (food_groups)
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS food_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- -------------------------------------------------------------
-- 3. ตารางเมนูอาหาร (foods)
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS foods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name CHARACTER VARYING NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    requires_stock BOOLEAN DEFAULT FALSE,
    category_id BIGINT REFERENCES food_groups(id) ON DELETE SET NULL
);

-- -------------------------------------------------------------
-- 4. ตารางราคาอาหารตามกลุ่มลูกค้า (food_prices)
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS food_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_id BIGINT NOT NULL REFERENCES foods(id) ON DELETE CASCADE,
    customer_group_id BIGINT NOT NULL REFERENCES customer_groups(id) ON DELETE CASCADE,
    price NUMERIC NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- -------------------------------------------------------------
-- 5. ตารางสต็อกวัตถุดิบ (food_stocks)
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS food_stocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_name TEXT NOT NULL,
    quantity NUMERIC NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- -------------------------------------------------------------
-- 6. ตารางการผูกสูตรอาหารกับวัตถุดิบ (food_mappings)
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS food_mappings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_id BIGINT REFERENCES foods(id) ON DELETE CASCADE,
    stock_name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- -------------------------------------------------------------
-- 7. ตารางสถานที่/สาขา (locations)
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- -------------------------------------------------------------
-- 8. ตารางโซนภายในสาขา (zones)
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS zones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    location_id BIGINT REFERENCES locations(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- -------------------------------------------------------------
-- 9. ตารางตัวเลือกเสริม (modifiers)
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS modifiers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price NUMERIC NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- -------------------------------------------------------------
-- 10. ตารางออร์เดอร์ลูกค้า (orders)
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    customer_group TEXT,
    total_price NUMERIC,
    total_qty BIGINT,
    items JSONB,
    phone TEXT,
    location_name TEXT,
    zone_name TEXT,
    order_date DATE,
    status TEXT
);
