-- --------------------------------------------------------
-- ไฟล์: schema.sql (ฉบับปรับปรุงสมบูรณ์ รองรับระบบตัดสต็อก)
-- --------------------------------------------------------

-- 1. ตารางกลุ่มลูกค้า
CREATE TABLE IF NOT EXISTS customer_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. ตารางผูกสูตรอาหารกับวัตถุดิบ
CREATE TABLE IF NOT EXISTS food_mappings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_id BIGINT,
    stock_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. ตารางราคาอาหารตามกลุ่ม
CREATE TABLE IF NOT EXISTS food_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_id BIGINT,
    customer_group_id BIGINT,
    price NUMERIC,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. ตารางสต็อกวัตถุดิบ
CREATE TABLE IF NOT EXISTS food_stocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_name TEXT,
    quantity NUMERIC DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 5. ตารางรายการอาหาร
CREATE TABLE IF NOT EXISTS foods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(255),
    name VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    requires_stock BOOLEAN
);

-- 6. ตารางสถานที่/โซนจัดส่ง
CREATE TABLE IF NOT EXISTS locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 7. ตารางประวัติการสั่งซื้อ (เพิ่ม status สำหรับระบบเช็คและตัดสต็อก)
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    customer_group TEXT,
    total_price NUMERIC,
    total_qty BIGINT,
    items JSONB,
    phone TEXT,
    location_name TEXT,
    zone_name TEXT,
    order_date DATE,
    status TEXT DEFAULT 'pending'
);

-- 8. ตารางโซนย่อยในสถานที่
CREATE TABLE IF NOT EXISTS zones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    location_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
